baseURL = "https://luvke0214.github.io/yuxiangtao-site/"
title = "Student"
languageCode = "en-us"
theme = "PaperMod"
enableRobotsTXT = true

# ✅ 关键：强制用绝对 URL，避免 ./ 这种相对路径
canonifyURLs = true
relativeURLs = false

[params]
  env = "production"
  defaultTheme = "auto"
  disableThemeToggle = false

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 20
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 30
  [[menu.main]]
    name = "Academics/Skills"
    url = "/academics/"
    weight = 40
  [[menu.main]]
    name = "Works"
    url = "/works/"
    weight = 50

